---
dependency:
  name: galaxy
lint: |
  yamllint molecule/default/converge.yml
  ansible-lint molecule/default/converge.yml
driver:
  name: docker
platforms:
  - name: instance
    image: centos/systemd
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
